# Generated by Django 4.1.5 on 2023-08-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='carimage',
            field=models.ImageField(default=None, upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='cardesc',
            field=models.CharField(default='abc', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cars',
            name='carname',
            field=models.CharField(default='abc', max_length=50),
        ),
    ]
