# Generated by Django 4.1.5 on 2023-08-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cars_carimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='carimage',
            field=models.ImageField(default='cars/media/images/pizza-g8b47044f6_1280.jpg', upload_to='media/images'),
        ),
    ]
